# Generated by Django 3.1.4 on 2020-12-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FontFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family_name', models.CharField(max_length=100)),
                ('path_to_font_family', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=100)),
                ('checked_out', models.BooleanField(default=False)),
                ('font_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fonts.fontfamily')),
            ],
            options={
                'ordering': ['font_family'],
            },
        ),
    ]
