# Generated by Django 3.1.4 on 2020-12-18 00:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FontFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family_creator_name', models.CharField(max_length=100)),
                ('font_family_name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=100)),
                ('font_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fonts.fontfamily')),
            ],
            options={
                'ordering': ['font_family'],
            },
        ),
    ]
