# Generated by Django 3.1.4 on 2020-12-18 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0002_font_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='assigned_to',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
