# Generated by Django 3.1.4 on 2020-12-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0003_font_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
