# Generated by Django 3.1.4 on 2020-12-23 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0004_auto_20201222_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='fontfamily',
            name='path_to_font_family',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
