# Generated by Django 3.1.4 on 2020-12-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0005_fontfamily_path_to_font_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='font',
            options={},
        ),
        migrations.RemoveField(
            model_name='font',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='fontfamily',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='fontfamily',
            name='font_family_name',
        ),
        migrations.RemoveField(
            model_name='fontfamily',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='fontfamily',
            name='font_family_creator_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
