# Generated by Django 3.1.4 on 2020-12-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0006_auto_20201224_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fontfamily',
            old_name='font_family_creator_name',
            new_name='font_family_name',
        ),
    ]
